[tools]
node = "20.16.0"
flyctl = "latest"

[tasks.clean]
run = 'rm -rf dist && rm -rf coverage'

[tasks.build]
run = 'node_modules/.bin/tsc --project tsconfig.json'
sources = ['src/**/*']
outputs = ['dist/**/*']

[tasks.run]
run = "node dist/cmd/index.js start"
depends = ['build']
alias = 'default'

[tasks.register]
run = "node dist/cmd/index.js register"
depends = ['build']

[tasks.test]
run = "node_modules/.bin/jest"
